PUT http://localhost:8080/put/Anmol?lastName=Dhiman

###
POST http://localhost:8080/post
Content-Type: application/json

{
  "firstName": "Anmol",
  "lastName": "Dhiman"
}

###
GET http://localhost:8080/param/Anmol

###
GET http://localhost:8080/query?name=Anmol

###
GET localhost:8080/